fix: modal position
worldcoin/world-id-js pull request #8
Opened 2022-05-04 11:15 UTC by igorosip0v

## Changes

- Remove fixed `min-height` on `ModalWrapper`
- Remove overflow on `ModalWrapper`
- Change `SModalCTA` position to `absolute`

### Result
Main modal content is centered, CTA box below it.

https://user-images.githubusercontent.com/89008845/166670864-45e39c91-77cd-4e57-9c8e-3eb5999b1a45.mp4

2022-05-05 13:56 UTC, paolodamico requested changes
I think the ideal behavior we want here would be that when the secondary modal is dismissed (by moving to the next step), the main modal slides down to take the vertical center of the screen. That way when both modals are shown, they also look centered.

Also with these changes, the modals now get cut off in small heights and you can't scroll to see them properly.

2022-05-05 16:26 UTC, igorosip0v commented
@paolodamico Hi!
I think I managed to do it the way you described. This is how it looks now: 


https://user-images.githubusercontent.com/89008845/166968859-3e1777eb-9c03-4295-8a61-428eff2bd902.mp4

2022-05-05 17:44 UTC, tino-otto approved these changes

2022-05-06 13:11 UTC, paolodamico approved these changes
great stuff! looks amazing; last minor detail is that if the screen is particularly short, everything gets cropped and you can't scroll, but let's fix that on a separate PR

2022-05-06 16:13 UTC, merged